[package]
name = "portfolio-yew-app"
version = "0.1.0"
authors = ["Gabriel <gfp001@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18.0"
num-bigint = "0.4"
